### ISSUE TITLE
Konna body

### ISSUE THREAD

**Issue by krazyjakee** [NodotProject/konna3d#12]
![image](https://github.com/NodotProject/konna3d/assets/623463/6fa5186a-3515-4080-a977-77381c766b21)

- Idle
- Walking
- Jump
- Crouch
- Swim

**Comment by tossudev** [comment]
![konna_run](https://github.com/NodotProject/konna3d/assets/122676864/784fbc76-0e5c-4623-8677-88df884b8a0f)
![konna_jump](https://github.com/NodotProject/konna3d/assets/122676864/fa6b824b-604f-4202-8133-1cf21979644d)
![konna_fishing](https://github.com/NodotProject/konna3d/assets/122676864/fcb43cae-a760-47a1-90f4-079bf7155173)
![konna_swim](https://github.com/NodotProject/konna3d/assets/122676864/2bc5fb11-afef-4c62-bf5c-2df6aa92d374)

**Comment by krazyjakee** [comment]
Thanks so much! Sorry for the late reply.

**Comment by krazyjakee** [comment]
[konna.zip](https://github.com/NodotProject/konna3d/files/12589628/konna.zip)
![image](https://github.com/NodotProject/konna3d/assets/623463/4eb6fce4-86eb-4e02-993c-8687deca28af)
